# Generated by Django 5.1.6 on 2025-02-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-id",), "verbose_name": "Order"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order Item"},
        ),
    ]
